# use rest_framework to create an API for the analytics bot
import os
import sys

# Add analytics_bot path to sys.path so that 'src' imports resolve correctly
analytics_bot_dir = os.path.dirname(os.path.abspath(__file__))
if analytics_bot_dir not in sys.path:
    sys.path.insert(0, analytics_bot_dir)
    
from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework.response import Response
from asgiref.sync import async_to_sync
import analytics_bot.src.session as _sess

from analytics_bot.src.pipeline import ask_retail_rag_ui    

@api_view(['POST','GET'])
def chat(request):
    question = request.data.get('question')
    print("question", question)
    history = request.data.get('history', [])
    use_viz = request.data.get('use_viz', True)
    use_reco = request.data.get('use_reco', True)
    use_cache = request.data.get('use_cache', True)
    
    if not question:
        return Response({'error': 'Question is required'}, status=400)
        
    # Get/initialize session
    session = _sess.get_session()
    
    # Propagate history if provided
    if history and isinstance(history, list):
        session._conversation_history.clear()
        for h in history:
            if isinstance(h, dict):
                if "question" in h:
                    session._conversation_history.append({
                        "question": h.get("question", ""),
                        "rewritten": h.get("rewritten", h.get("question", "")),
                        "columns": h.get("columns", []),
                        "success": h.get("success", True)
                    })
                elif h.get("role") == "user":
                    session._conversation_history.append({
                        "question": h.get("content", ""),
                        "rewritten": h.get("content", ""),
                        "columns": [],
                        "success": True
                    })

    async def run_pipeline():
        _sess.set_session(session)
        last_chunk = None
        async for chunk in ask_retail_rag_ui(
            question=question,
            use_viz=use_viz,
            use_reco=use_reco,
            use_cache=use_cache
        ):
            last_chunk = chunk
        return last_chunk

    try:
        last_chunk = async_to_sync(run_pipeline)()
        if last_chunk:
            response_text = last_chunk.get("chat_text") or last_chunk.get("summary") or ""
            return Response({
                "response": response_text,
                "result_html": last_chunk.get("result_html", ""),
                "chart_html": last_chunk.get("chart_html", ""),
                "chart_json": last_chunk.get("chart_json", ""),
                "reco_text": last_chunk.get("reco_text", ""),
                "followup": last_chunk.get("followup", []),
                "summary": last_chunk.get("summary", ""),
                "tokens_used": last_chunk.get("tokens_used", 0),######added here#########################################3
                "done": last_chunk.get("done", False),
            })
        else:
            return Response({"error": "No response generated by the analytics pipeline"}, status=500)
    except Exception as e:
        return Response({"error": str(e)}, status=500)

def home(request):
    return render(request, "ui.html")
